#!/usr/bin/env bash

if [ -n "$DROPBOX_ACCESS_TOKEN" ]; then
  cat << EOF > .dropbox_uploader
OAUTH_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
EOF
  if [ -d world ]; then
    echo "Saving world..."
    tar -czvf backup.tar.gz world
    bin/dropbox_uploader.sh upload backup.tar.gz /testm123
    rm backup.tar.gz
  else
    echo "Fetching world..."
    if bin/dropbox_uploader.sh download /testm123/backup.tar.gz
    then
      tar -xzvf backup.tar.gz
      rm backup.tar.gz
    fi
  fi
  rm .dropbox_uploader
fi
